print('hello henry')
print("type where you want to go")
a=input()
if a=='typing':
  print("finding typing...")
  print("typing found")
  secretword=input()
  cat=open('h.txt', 'x')
  cat.write(secretword)
  if secretword=='cats are the best pet in the world':
    print("welcome to games")
    print("what game")
    print("warrior cat game?")
    game=input()
    if game=='warrior cat game':
      print("welcome to warriors world hunting traning")
      print("wich cat do you want to use hawkpelt, fluffyfur, firestar, softpelt, cloudtail,")
      cat=input()
      print('ok lets go get' , cat)
      h=input()
      print("ok we are at the hunting grounds type yes i do see some")
      ab=input()
      print("you are right i" , ab)
      print("prey")
      print("ok lets go catch it")
      zxyuyfdehufhfeuyhydhsrfhgas=input()
      print("good job catching it")
      print("ok now should we eat that nice big mouse type if yes type yes we should if no type no we should not")
      c=input()
      print("i agree " , c)
      print("eat it")
      print("game finishd")